In [16]:
import numpy as np

column1 = []
column2 = []
with open('input_file.txt') as file:
    for line in file:
        splitted_line = line.split()
        column1.append(int(splitted_line[0]))
        column2.append(int(splitted_line[1]))

column1 = np.array(column1)
column2 = np.array(column2)

np.sum(np.abs(np.sort(column1)-np.sort(column2)))


1646452

In [17]:
column1

array([80414, 17250, 23063, 89663, 27237, 81505, 67427, 95906, 19112,
       92811, 13558, 88090, 78043, 97013, 61919, 72566, 35301, 74588,
       85685, 16993, 76769, 77423, 71971, 58114, 53172, 88833, 77532,
       64134, 76211, 53521, 33006, 78562, 71763, 33704, 72748, 52182,
       58871, 86416, 92658, 53632, 65521, 39351, 53327, 71673, 79947,
       34434, 72493, 70108, 75643, 32893, 95833, 36562, 93015, 26814,
       47888, 20711, 30854, 84916, 87347, 57354, 27380, 66813, 26583,
       11010, 49768, 75348, 51341, 88498, 87012, 38931, 60255, 26660,
       22304, 50828, 58198, 80389, 95968, 13821, 54447, 51614, 21626,
       51912, 67163, 68836, 93741, 19766, 53097, 52636, 96518, 43414,
       42478, 83274, 10577, 96150, 61460, 52954, 86111, 67981, 89005,
       25240, 52033, 57669, 91455, 46929, 46377, 60937, 51158, 99819,
       98623, 58882, 51995, 11409, 81603, 66492, 57941, 87499, 24055,
       62911, 88178, 86394, 90516, 85871, 81993, 51752, 69157, 61057,
       11966, 69037,

In [4]:
a = np.array([1,2,3])
b = np.array([2,3,4])
b-a

array([1, 1, 1])

In [6]:
a = np.array([22,2,3])

np.sort(a)

array([ 2,  3, 22])

In [8]:
column1

array(['80414'], dtype='<U5')

In [10]:
column1[-1]

80414

In [14]:
column1 = []
column2 = []
with open('input_file.txt') as file:
    line = file.read()
    splitted_line = line.split()
    column1.append(int(splitted_line[0]))
    column2.append(int(splitted_line[1]))

#column1 = np.array(column1)
#column2 = np.array(column2)


In [15]:
column1

[80414]

In [29]:
from collections import Counter

a = Counter(list(column2))
summa = 0
for i in column1:
   summa += i*a[i]

summa    

23609874

In [26]:
len(set(list(column1)))

1000

In [28]:
len(column1)

1000